name: Build & Push Images

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    environment:
      name: production
      url: https://poetrystream.qzz.io

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push backend
        run: |
          IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}/backend:latest" | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_NAME ./backend
          docker push $IMAGE_NAME

      - name: Build & push frontend
        run: |
          IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}/frontend:latest" | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_NAME ./frontend
          docker push $IMAGE_NAME